version: '3'

vars:
  ENV_FILE: .env.local
  ENV_EXAMPLE: .env.example

tasks:
  dev:
    desc: "Start the app locally without trying to run Supabase locally."
    run: once
    cmds:
      - task: setup:init
      - task: setup:env
      - cmd: npm run dev

  setup:init:
    desc: "Install dependencies"
    cmds:
      - cmd: npm install
      - cmd: npm run prepare

  setup:env:
    desc: "Create .env.local if missing"
    cmds:
      - cmd: |
          if [ ! -f {{.ENV_FILE}} ]; then
            cp {{.ENV_EXAMPLE}} {{.ENV_FILE}}
            echo "Created {{.ENV_FILE}}."
          fi

  db:reset:
    desc: "Not used anymore — just here as a placeholder."
    cmds:
      - cmd: echo "Database reset skipped — using Supabase Cloud."
